### ISSUE TITLE
Injection not always being executed in 1.6.0

### ISSUE THREAD

**Issue by mikestead** [massiveinteractive/minject#36]
We've had to drop back to v1.5.2 as when using v1.6.0 via mmvc we have come across injections which have not been executed, and no error is thrown until you try to access the property and it's null. In our case in `onRegister`.

**Comment by thomasuster** [comment]
Hey @mikestead . Could you boil down a breaking test for me or gist? I'm happy to help.

**Comment by mikestead** [comment]
Sorry don't have time to do that atm. I did spend a bit of time trying initially but couldn't pinpoint the cause, only the issue. We have a private codebase where this is manifesting so hopefully one of us will get some time to investigate soon.

**Comment by dpeek** [comment]
This is fixed in 1.6.1, which is basically a re-release of 1.5.2 (master has been rolled back)

I did try debugging it, but something subtle was going on with the changes to child injectors (I think) that I couldn't track down. Focusing on 2.0 now, which will have the optimisations from 1.6 without the child injector changes (and a lot of other cools stuff)
